---
- name: Install dnf packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - mc
    - nginx
    - git
    - tar
    - pip

- name: State nginx on Rocky
  when: enable_enginx
  ansible.builtin.systemd:
    name: nginx
    state: stopped
    enabled: false

- name: Disable SELinux on Rocky
  ansible.posix.selinux:
    configfile: /etc/selinux/config
    update_kernel_param: true
    state: disabled

- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Stop firewalld on Rocky
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Add signing key
  ansible.builtin.rpm_key:
    key: 'https://download.docker.com/linux/centos/gpg'
    state: present

- name: Add repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: 'https://download.docker.com/linux/centos/$releasever/$basearch/stable'
    enabled: true
    gpgcheck: true
    gpgkey: 'https://download.docker.com/linux/centos/gpg'

- name: Install Docker
  ansible.builtin.yum:
    name:
      - docker-ce-{{ docker_ce_ver }}
      - docker-ce-cli-{{ docker_ce_ver }}
      - containerd.io-{{ containerd_ver }}
    update_cache: true

- name: Start Docker
  ansible.builtin.service:
    name: 'docker'
    enabled: true
    state: started

- name: Install python docker packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - "docker==6.1.3"
    - "docker-compose"